# Generated by Django 3.0.8 on 2020-10-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('S', 'shirt'), ('J', 'jacket'), ('H', 'hat'), ('SK', 'skateboard')], default='S', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('B', 'both'), ('M', 'men'), ('W', 'woman')], default='B', max_length=20),
        ),
    ]
