# Generated by Django 3.0.8 on 2020-10-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_auto_20201002_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='oneSize',
            field=models.BooleanField(default=False),
        ),
    ]
