# Generated by Django 3.0.8 on 2020-10-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_products_onesize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
